### ISSUE TITLE
add electron-packager  examples

### ISSUE THREAD

**Issue by pookpal** [egoist/vuepack#137]
eg.

**Comment by pookpal** [comment]
create new folder in app such as imgs, and then add icon both ico and icns

"buildAll": "electron-packager ./app <appName> --all --out ./OutApp --version 1.4.6 --overwrite --icon=./app/imgs/logo.ico",


"buildWin": "electron-packager ./app <appName> --platform=win32  --arch=ia32,x64 --out ./OutApp --version 1.4.6 --overwrite --icon=./app/imgs/logo.ico",

"buildMac": "electron-packager ./app <appName> --platform=mas  --arch=x64 --out ./OutApp --version 1.4.6 --overwrite --icon=./app/imgs/logo.icns",

**Comment by archaistvolts** [comment]
Hello and thank you for the example scripts.  I am trying to use the buildWin script you provided, leaving off the icon as I'm having troubles with that for now.  This allows the build to complete.  But when i run the created exe, I keep getting the error below.  The error message 'SyntaxError: Unexpected token import' indicates that the javascript interpreter isn't groking import (es5 feature I think).  This app has been working fine when started with `npm run app`.  Any ideas what the problem could be?  I made sure to `npm run build` before release building but I don't think that is the problem...
```
[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
C:\Users\Travis\Documents\Code\Projects\miner-manager\release-builds\Miner Man-win32-ia32\resources\app\client\index.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import './promise-polyfill'
                                                                                                                                                           ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Object.<anonymous> (C:\Users\Travis\Documents\Code\Projects\miner-manager\release-builds\Miner Man-win32-ia32\resources\electron.asar\browser\init.js:171:8)
    at Object.<anonymous> (C:\Users\Travis\Documents\Code\Projects\miner-manager\release-builds\Miner Man-win32-ia32\resources\electron.asar\browser\init.js:173:3)
    at Module._compile (module.js:571:32)
```

**Comment by archaistvolts** [comment]
I was able to get this working by copying package.json into app folder and changing a line
```
  "main": "client/index.js",
```
to 
```
  "main": "index.js",
```
here is my script entry: 
```
"buildWin": "electron-packager ./app --platform=win32 --arch=ia32,x64 --out ./release-builds --version 0.1.0 --overwrite",
```

**Comment by mengxiaof** [comment]
I want to know how to build mas

**Comment by motin** [comment]
[electron-builder](https://github.com/electron-userland/electron-builder) seems more straightforward to use

**Comment by motin** [comment]
Maybe this issue can be closed in favor of https://github.com/egoist/vuepack/issues/115?
