### ISSUE TITLE
`htmlWebpackPlugin is not defined` error during initialization

### ISSUE THREAD

**Issue by imdreamrunner** [egoist/vuepack#148]
Dear all,

I was trying out vuepack using `sao`. Below is the error i got. Do you have any idea? Many thanks!

```
➜  Documents sao egoist/vuepack hello-vue  
? Project name hello-vue
? Project description My Superb Vue Project
? Author Ivor Zhou
? Do you want to support ESLint? Yes
? Generate components in JSX format? No
? Support Electron? No
? Add testcafe to run integration tests? Yes
error ReferenceError: ejs:5
    3|   <head>
    4|     <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
 >> 5|     <title><%= htmlWebpackPlugin.options.title %></title>
    6|   </head>
    7|   <body>
    8|     <div id="app"></div>

htmlWebpackPlugin is not defined
    at eval (eval at compile (/Users/ivorz/.config/yarn/global/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:26)
    at Object.returnedFn [as fn] (/Users/ivorz/.config/yarn/global/node_modules/ejs/lib/ejs.js:580:17)
    at Transformer.render (/Users/ivorz/.config/yarn/global/node_modules/jstransformer/index.js:289:25)
    at run (/Users/ivorz/.config/yarn/global/node_modules/kopy/dist/kopy.common.js:158:54)
    at Promise.all.fileList.map.relative (/Users/ivorz/.config/yarn/global/node_modules/kopy/dist/kopy.common.js:145:49)
    at Array.map (native)
    at Ware.ctx (/Users/ivorz/.config/yarn/global/node_modules/kopy/dist/kopy.common.js:145:33)
    at Ware.<anonymous> (/Users/ivorz/.config/yarn/global/node_modules/wrap-fn/index.js:75:16)
    at Ware.<anonymous> (/Users/ivorz/.config/yarn/global/node_modules/wrap-fn/index.js:57:27)
    at next (/Users/ivorz/.config/yarn/global/node_modules/ware/lib/index.js:85:20)
```

**Comment by egoist** [comment]
Try `sao@0.21.10`
