### ISSUE TITLE
How to extract css code into single css file in dev mode?

### ISSUE THREAD

**Issue by lavezzi1** [egoist/vuepack#61]
Hello, thanks for boilerplate!

So the question in the title. Would be awesome if you help with that.

**Comment by egoist** [comment]
Why do you need this? extracted css in dev mode doesn't have Hot Module Replacement support

**Comment by lavezzi1** [comment]
@egoist Oh sorry, I didn't know that. I faced with problem when I run npm run build

```
ERROR in ./client/rucksack/background-color.css
Module build failed: ReferenceError: window is not defined
    at /code/webpack/new-project/node_modules/style-loader/index.js!/code/webpack/new-project/node_modules/css-loader/index.js?-autoprefixer!/code/webpack/new-project/node_modules/postcss-loader/index.js!/code/webpack/new-project/client/rucksack/background-color.css:99:30
    at /code/webpack/new-project/node_modules/style-loader/index.js!/code/webpack/new-project/node_modules/css-loader/index.js?-autoprefixer!/code/webpack/new-project/node_modules/postcss-loader/index.js!/code/webpack/new-project/client/rucksack/background-color.css:94:47
    at module.exports (/code/webpack/new-project/node_modules/style-loader/index.js!/code/webpack/new-project/node_modules/css-loader/index.js?-autoprefixer!/code/webpack/new-project/node_modules/postcss-loader/index.js!/code/webpack/new-project/client/rucksack/background-color.css:116:68)
    at Object.<anonymous> (/code/webpack/new-project/node_modules/style-loader/index.js!/code/webpack/new-project/node_modules/css-loader/index.js?-autoprefixer!/code/webpack/new-project/node_modules/postcss-loader/index.js!/code/webpack/new-project/client/rucksack/background-color.css:400:36)
    at __webpack_require__ (/code/webpack/new-project/node_modules/style-loader/index.js!/code/webpack/new-project/node_modules/css-loader/index.js?-autoprefixer!/code/webpack/new-project/node_modules/postcss-loader/index.js!/code/webpack/new-project/client/rucksack/background-color.css:21:30)
    at /code/webpack/new-project/node_modules/style-loader/index.js!/code/webpack/new-project/node_modules/css-loader/index.js?-autoprefixer!/code/webpack/new-project/node_modules/postcss-loader/index.js!/code/webpack/new-project/client/rucksack/background-color.css:65:18
    at Object.<anonymous> (/code/webpack/new-project/node_modules/style-loader/index.js!/code/webpack/new-project/node_modules/css-loader/index.js?-autoprefixer!/code/webpack/new-project/node_modules/postcss-loader/index.js!/code/webpack/new-project/client/rucksack/background-color.css:68:10)
    at Module._compile (module.js:570:32)
    at Object.exec (/code/webpack/new-project/node_modules/webpack/lib/NormalModule.js:94:6)
    at Object.<anonymous> (/code/webpack/new-project/node_modules/extract-text-webpack-plugin/loader.js:101:21)
    at Compiler.<anonymous> (/code/webpack/new-project/node_modules/webpack/lib/Compiler.js:251:10)
    at /code/webpack/new-project/node_modules/webpack/lib/Compiler.js:442:12
    at next (/code/webpack/new-project/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/code/webpack/new-project/node_modules/extract-text-webpack-plugin/loader.js:82:4)
    at next (/code/webpack/new-project/node_modules/tapable/lib/Tapable.js:83:14)
    at Compiler.<anonymous> (/code/webpack/new-project/node_modules/webpack/lib/CachePlugin.js:61:4)
    at Compiler.applyPluginsAsync (/code/webpack/new-project/node_modules/tapable/lib/Tapable.js:85:13)
    at Compiler.<anonymous> (/code/webpack/new-project/node_modules/webpack/lib/Compiler.js:439:9)
    at Compilation.applyPluginsAsync (/code/webpack/new-project/node_modules/tapable/lib/Tapable.js:73:70)
    at Compilation.<anonymous> (/code/webpack/new-project/node_modules/webpack/lib/Compilation.js:621:18)
    at Compilation.applyPluginsAsync (/code/webpack/new-project/node_modules/tapable/lib/Tapable.js:73:70)
    at Compilation.<anonymous> (/code/webpack/new-project/node_modules/webpack/lib/Compilation.js:612:10)
    at next (/code/webpack/new-project/node_modules/tapable/lib/Tapable.js:81:11)
    at Compilation.<anonymous> (/code/webpack/new-project/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:144:4)
    at Compilation.applyPluginsAsync (/code/webpack/new-project/node_modules/tapable/lib/Tapable.js:85:13)
    at Compilation.<anonymous> (/code/webpack/new-project/node_modules/webpack/lib/Compilation.js:607:9)
    at Compilation.applyPluginsAsync (/code/webpack/new-project/node_modules/tapable/lib/Tapable.js:73:70)
    at Compilation.<anonymous> (/code/webpack/new-project/node_modules/webpack/lib/Compilation.js:603:8)
    at Compilation.applyPluginsAsync (/code/webpack/new-project/node_modules/tapable/lib/Tapable.js:73:70)
    at Compilation.seal (/code/webpack/new-project/node_modules/webpack/lib/Compilation.js:551:7)

ERROR in /code/webpack/new-project/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!/code/webpack/new-project/node_modules/style-loader/index.js!/code/webpack/new-project/node_modules/style-loader/index.js!/code/webpack/new-project/node_modules/css-loader/index.js?-autoprefixer!/code/webpack/new-project/node_modules/postcss-loader/index.js!/code/webpack/new-project/client/rucksack/background-color.css doesn't export content
```

I just imported css framework (which contains only css) in my entry file like

```
import rucksack from './rucksack'
```

And /rucksack/index.js looks like this

```
import './background-color.css'
...
```

can you help please?

**Comment by egoist** [comment]
It should work now ;)
