### ISSUE TITLE
Webpack error after upgrading to vue 2.1

### ISSUE THREAD

**Issue by ryanmclaughlin** [egoist/vuepack#68]
For some reason, trying to run `npm run dev` I'm getting this webpack error.

```
> gamewatch@0.1.0 dev /Users/mack/Projects/gamewatch
> node build/server.js


/Users/mack/Projects/gamewatch/node_modules/webpack/lib/webpack.js:17
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'vue'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           vue: ...
         }
       })
     ]
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (/Users/mack/Projects/gamewatch/node_modules/webpack/lib/webpack.js:17:9)
    at Object.<anonymous> (/Users/mack/Projects/gamewatch/build/server.js:17:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

The only thing I've changed in the webpack configuration is added sass support in `webpack.base.js` after `postcss: config.postcss` and before `plugins`:

```
  vue: {
    loaders: {
      sass: "vue-style-loader!css-loader!sass?indentedSyntax"
    },
    postcss: config.postcss
  },
```

**Comment by egoist** [comment]
Did you upgrade webpack? related to https://github.com/egoist/vuepack/issues/42 and https://github.com/egoist/vuepack/issues/65

**Comment by ryanmclaughlin** [comment]
I'm using the one in the current version of this repo: `"webpack": "^2.1.0-beta.22"`

EDIT: running `beta.20` worked on both dev and build. Erhg, betas, sorry for the duplicate issue. Thanks @egoist

**Comment by egoist** [comment]
it should be `"webpack": "2.1.0-beta.22"`

**Comment by ryanmclaughlin** [comment]
Yeah, that one was giving me loads of issues. Simply changing to .20 works fine.
