### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by ryandeussing** [egoist/vuepack#7]
I'm getting this error when I try to run any command with `vue`:

``` javascript
vue -h
/usr/local/lib/node_modules/vuepack/bin/vuepack:10
  console.log(`${pkg.name.magenta} ~ ${pkg.version.cyan}`)
              ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Thanks in advance for help with this.

**Comment by egoist** [comment]
Your node version? This does only support node 4+.

**Comment by ryanaponte** [comment]
That's the issue ;)
