### ISSUE TITLE
Doesn't work when electron is not present

### ISSUE THREAD

**Issue by JiriChara** [egoist/vuepack#70]
```javascript
/home/jiri/Projects/chara.vip/build/server.js:38
  fse.ensureDirSync(path.dirname(file))
  ^

ReferenceError: fse is not defined
    at devMiddleWare.waitUntilValid (/home/jiri/Projects/chara.vip/build/server.js:38:3)
    at continueBecauseBundleAvailable (/home/jiri/Projects/chara.vip/node_modules/webpack-dev-middleware/middleware.js:94:5)
    at Array.forEach (native)
    at /home/jiri/Projects/chara.vip/node_modules/webpack-dev-middleware/middleware.js:93:8
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

The problem is that fse dependency is loaded just for electron

https://github.com/egoist/vuepack/blob/master/template/build/server.js#L44

**Comment by JiriChara** [comment]
thanks :+1:
