### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by alexsinfarosa** [egoist/vuepack#76]
Hi, after a fresh install of vuepack I ran `npm run dev` and I got this:

> node build/server.js

webpack: wait until bundle finished:
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::4000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at Function.listen (/Users/alex/code/mio/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/alex/code/mio/build/server.js:51:5)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3

**Comment by egoist** [comment]
Seems port 4000 is already in use?

**Comment by alexsinfarosa** [comment]
Wow! you are fast! I am gonna try to reboot my system and see what happens, but i think you are probably right. Thanks!

**Comment by egoist** [comment]
I will update it to use a free port if 4000 is in use.

**Comment by alexsinfarosa** [comment]
Yes, that was the problem, but I had to reboot the system to fix it. Thanks a lot!

**Comment by alexsinfarosa** [comment]
Oh weird!! Now I get an error `unmet peer dependency: eslint-plugin-vue`

**Comment by alexsinfarosa** [comment]
I just installed `eslint-plugin-vue` and it fixed the problem.

**Comment by egoist** [comment]
@alexsinfarosa that error has been fixed too https://github.com/egoist/vuepack/commit/551bcebee2df5f8c0b889f0dfed2fac3a8881a6e
