### ISSUE TITLE
build model failed!

### ISSUE THREAD

**Issue by cddsgtc** [egoist/vuepack#93]
信息如下：
```
PS I:\practice\vue-cli\cdd> yarn build
yarn build v0.18.1
$ webpack --config build/webpack.prod.js
'rm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
�������ļ�
child_process.js:526
    throw err;
    ^

Error: Command failed: rm -rf dist/
'rm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at Object.<anonymous> (I:\practice\vue-cli\cdd\build\webpack.prod.js:19:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (modul
```

**Comment by cddsgtc** [comment]
使用npm build报错，

**Comment by egoist** [comment]
https://github.com/egoist/vuepack#for-windows-users

**Comment by cddsgtc** [comment]
@egoist 
yea, so i use git bash on the winOS and get the results.
