### ISSUE TITLE
'npm run dev' results in SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by mark-de-haan** [egoist/vuepack#95]
I followed the vuex-cli steps, but when running `npm run dev` I encountered the following error:

```
module.exports = class LogPlugin {
                 ^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/mdehaan/git/vue/vuex-project/build/server.js:9:19)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3

npm ERR! Darwin 13.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v5.3.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! vuex-project@0.1.0 dev: `node build/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vuex-project@0.1.0 dev script 'node build/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vuex-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/server.js
```

Running with Node v5.4.0
Running with NPM v4.0.5

During setup:
ESlint: no
JSX: yes
Electron: no

Also fails with:
ESlint: yes
JSX: no
Electron: no

**Comment by egoist** [comment]
use node 6 or higher

**Comment by mark-de-haan** [comment]
It would be a better fix to add `'use-strict'` to **log-plugin.js** then to not support ATLEAST node 5, but il switch to another vuex starter kit

**Comment by alexzorin** [comment]
Bit me too.

README:

```
You'd better have node >=4 and npm >=3 installed:
```

Would be nice to either update the README or take Mark's suggestion, since it's broken out of the box on node <6.

**Comment by egoist** [comment]
@alexzorin yep, I will do it later
